from pathlib import Path
from html import escape

ROOT=Path('/home/ayron/khs-ai-portfolio')
SITE='https://ayron.in'
ROUTES=[('/', 'Home'),('/homelab/','Home Lab'),('/networking/','Networking'),('/ai/','AI & Development'),('/projects/','Projects'),('/tools/','Tools'),('/about/','About')]

def nav(current):
    return ''.join(f'<a href="{route}"'+(' aria-current="page"' if route==current else '')+f'>{escape(label)}</a>' for route,label in ROUTES)

def footer():
    return '<footer class="site-footer"><div class="wrap footer-row"><span><b>AYRON JINS / LAB</b> — Personal engineering portfolio</span><span class="footer-nav"><a href="/">HOME</a><a href="/homelab/">HOME LAB</a><a href="/networking/">NETWORKING</a><a href="/ai/">AI &amp; DEVELOPMENT</a><a href="/projects/">PROJECTS</a><a href="/tools/">TOOLS</a><a href="/about/">ABOUT</a><a href="/privacy/">PRIVACY</a><a href="/site-info/">SITE INFO</a><a href="mailto:Ayronjins4@gmail.com">EMAIL</a></span><span>© <span id="current-year">2026</span> AYRON JINS</span></div></footer>'

def page(route,title,description,page,body):
    canonical=SITE+route
    return f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(description,quote=True)}"><meta name="robots" content="index,follow"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description,quote=True)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{SITE}/assets/ayron-jins-portfolio-og.png"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/tools.css"><script async src="/analytics/script.js" data-website-id="68eb35df-10a6-45d6-8f0f-3e3628b84cfc" data-host-url="{SITE}/analytics"></script><script src="/assets/site-core.js" defer></script><script src="/assets/tools.js" defer></script></head><body class="page page-tools page-{page}"><a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><div class="wrap nav"><a class="brand" href="/" aria-label="Ayron Jins home"><i class="brand-mark" aria-hidden="true"></i><span>AYRON JINS / LAB</span></a><nav class="nav-links" id="primary-nav" aria-label="Primary navigation">{nav(route)}</nav><div class="header-status"><i class="status-dot" aria-hidden="true"></i><span>SYSTEM: ONLINE</span></div><button class="menu" id="menu" type="button" aria-label="Open navigation" aria-controls="primary-nav" aria-expanded="false">☰</button></div></header>{body}{footer()}</body></html>'''

def routebar(label,index): return f'<div class="page-routebar wrap"><a href="/">← HOME</a><span>{index} / {escape(label.upper())}</span></div>'

home='''<main id="main-content" tabindex="-1"><div class="tools-hero wrap"><div class="section-kicker">Tools Lab / Practical engineering utilities</div><h1 class="section-title">Inspect the systems<br><em>behind the interface.</em></h1><p class="section-intro">Three focused tools for understanding domains, networks and the web. Built with browser computation, open standards and bounded local infrastructure—no paid APIs and no black-box scoring.</p></div><section class="section"><div class="wrap"><div class="tools-lab-grid"><article class="tools-card"><span class="tool-number">01 / DOMAIN OBSERVATORY</span><h2>See the path from name to response.</h2><p>DNS records, certificate identity, TLS negotiation, HTTP behavior and security headers in one readable diagnostic.</p><div class="tool-tags"><span>DNS</span><span>TLS</span><span>HTTP</span><span>SECURITY</span></div><footer><b>SERVER DIAGNOSTIC</b><a href="/tools/domain-observatory/">OPEN →</a></footer></article><article class="tools-card"><span class="tool-number">02 / NETWORK ARCHITECT</span><h2>Design address space that fits.</h2><p>CIDR calculations, binary boundaries, subnet splitting and aligned VLSM allocation—all computed privately in your browser.</p><div class="tool-tags"><span>CIDR</span><span>SUBNETTING</span><span>VLSM</span><span>LOCAL ONLY</span></div><footer><b>BROWSER COMPUTATION</b><a href="/tools/network-architect/">OPEN →</a></footer></article><article class="tools-card"><span class="tool-number">03 / SITE INTELLIGENCE</span><h2>Read what a crawler sees.</h2><p>Technical metadata, canonical signals, robots policy, sitemaps and structured data with evidence instead of an invented SEO score.</p><div class="tool-tags"><span>HTTP</span><span>ROBOTS</span><span>SITEMAPS</span><span>JSON-LD</span></div><footer><b>BOUNDED CRAWLER</b><a href="/tools/site-intelligence/">OPEN →</a></footer></article></div></div></section><section class="section"><div class="wrap"><div class="tool-panel"><div class="tool-kicker">OPERATING PRINCIPLES</div><h2>Useful signals. Narrow capabilities.</h2><p class="tool-intro">The Network Architect never sends input to the server. The two public inspectors validate DNS destinations, block private ranges, pin connections to validated public addresses, limit redirects and response size, and retain no scan history.</p></div></div></section></main>'''

domain='''<main id="main-content" tabindex="-1"><div class="tool-shell wrap">{routebar("Domain Observatory","01") }<header class="tool-head"><div><div class="section-kicker">DNS / TLS / HTTP / SECURITY</div><h1 class="section-title">Domain Observatory.</h1><p class="tool-intro">Understand exactly what happens between a domain and the server behind it. Enter a public hostname; the diagnostic runs through a bounded, SSRF-resistant backend.</p></div><div class="tool-index">PUBLIC PATH<br>INSPECTOR</div></header><section class="tool-panel"><div class="tool-kicker">TARGET</div><h2>Start with a domain.</h2><form id="domain-form" class="tool-form"><div class="tool-field"><label for="domain-input">DOMAIN OR HTTPS URL</label><input id="domain-input" autocomplete="url" placeholder="example.com" inputmode="url"><div class="tool-help">Only public HTTP/HTTPS destinations on ports 80 and 443 are accepted.</div></div><button class="tool-btn primary" type="submit">INSPECT DOMAIN →</button></form><div id="domain-status" class="tool-status" hidden></div></section><section id="domain-results" class="tool-results" hidden aria-live="polite"></section></div></main>'''

network='''<main id="main-content" tabindex="-1"><div class="tool-shell wrap">{routebar("Network Architect","02") }<header class="tool-head"><div><div class="section-kicker">CIDR / SUBNETTING / VLSM / BROWSER-LOCAL</div><h1 class="section-title">Network Architect.</h1><p class="tool-intro">Design and understand IP networks visually. Every calculation stays in this browser; configuration data is never sent to the server.</p></div><div class="tool-index">NO API<br>NO UPLOAD</div></header><div class="network-layout"><section class="tool-panel"><div class="tool-kicker">01 / SUBNET CALCULATOR</div><h2>Find the boundary.</h2><form id="network-form" class="tool-form"><div class="tool-field"><label for="cidr-input">IP ADDRESS / CIDR</label><input id="cidr-input" value="192.168.1.20/24" placeholder="192.168.1.20/24"><div class="tool-help">Supports IPv4 CIDR, including the /31 and /32 edge cases.</div></div><button class="tool-btn primary" type="submit">CALCULATE →</button></form><div id="network-results" aria-live="polite"></div></section><section class="tool-panel"><div class="tool-kicker">02 / SUBNET SPLITTER</div><h2>Divide a parent.</h2><form id="split-form" class="tool-form"><div class="tool-field"><label for="split-input">PARENT NETWORK</label><input id="split-input" value="192.168.1.0/24"><label for="split-prefix">TARGET PREFIX</label><input id="split-prefix" type="number" min="0" max="32" value="26"></div><button class="tool-btn primary" type="submit">SPLIT →</button></form><div id="split-results" aria-live="polite"></div></section></div><section class="tool-panel" style="margin-top:12px"><div class="tool-kicker">03 / VLSM PLANNER</div><h2>Allocate the right-sized blocks.</h2><form id="vlsm-form"><div class="tool-field"><label for="vlsm-input">PARENT NETWORK</label><input id="vlsm-input" value="10.0.0.0/24"></div><div class="tool-field" style="margin-top:12px"><label for="vlsm-requests">REQUIREMENTS / NAME,HOSTS</label><textarea id="vlsm-requests">Engineering,100
Servers,50
Management,20
CCTV,10</textarea><div class="tool-help">Largest requirements are allocated first into aligned blocks. No data leaves the browser.</div></div><button class="tool-btn primary" type="submit" style="margin-top:12px">ALLOCATE VLSM →</button></form><div id="vlsm-results" aria-live="polite"></div></section></div></main>'''

site='''<main id="main-content" tabindex="-1"><div class="tool-shell wrap">{routebar("Site Intelligence Lab","03") }<header class="tool-head"><div><div class="section-kicker">HTTP / METADATA / CRAWL SIGNALS</div><h1 class="section-title">Site Intelligence Lab.</h1><p class="tool-intro">Inspect how a public website presents itself to browsers, crawlers and search engines. Findings are evidence-based, bounded and never a ranking promise.</p></div><div class="tool-index">MAX 1 MiB<br>MAX 5 REDIRECTS</div></header><section class="tool-panel"><div class="tool-kicker">TARGET</div><h2>Read a public page.</h2><form id="site-form" class="tool-form"><div class="tool-field"><label for="site-input">PAGE URL OR DOMAIN</label><input id="site-input" autocomplete="url" placeholder="https://example.com"><div class="tool-help">The server fetcher validates every DNS destination and redirect before connecting.</div></div><button class="tool-btn primary" type="submit">INSPECT SITE →</button></form><div id="site-status" class="tool-status" hidden></div></section><section id="site-results" class="tool-results" hidden aria-live="polite"></section></div></main>'''

tool_switcher='''<section class="tool-panel tool-switcher" aria-labelledby="more-tools"><div class="tool-kicker">TOOLS LAB / CONTINUE</div><h2 id="more-tools">Explore more tools.</h2><div class="tool-tags"><a href="/tools/domain-observatory/">Domain Observatory</a><a href="/tools/network-architect/">Network Architect</a><a href="/tools/site-intelligence/">Site Intelligence Lab</a></div></section>'''
for name in ['domain','network','site']:
    locals()[name]=locals()[name].replace('</main>',tool_switcher+'</main>',1)

pages=[('tools/index.html',page('/tools/','Tools Lab | Engineering Utilities by Ayron Jins','Practical browser and server-side engineering utilities for DNS, TLS, HTTP, subnetting, VLSM, websites and technical SEO.','gateway',home)),('tools/domain-observatory/index.html',page('/tools/domain-observatory/','Domain Observatory | DNS, TLS and HTTP Inspector','Inspect public DNS records, TLS certificates, HTTP responses and security headers with a bounded engineering diagnostic.','domain-observatory',domain)),('tools/network-architect/index.html',page('/tools/network-architect/','Network Architect | CIDR, Subnetting and VLSM Planner','Calculate CIDR networks, split subnets and design aligned VLSM allocations locally in the browser.','network-architect',network)),('tools/site-intelligence/index.html',page('/tools/site-intelligence/','Site Intelligence Lab | Technical Website Inspector','Inspect public HTTP metadata, robots.txt, sitemaps, canonical signals and structured data with safe bounded fetching.','site-intelligence',site))]
for rel,content in pages:
 p=ROOT/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content,encoding='utf-8')
print('built',len(pages),'Tools Lab pages')
