#!/usr/bin/env python3
"""Build evidence-based flagship case studies for the Ayron Jins portfolio."""
from pathlib import Path
from html import escape

ROOT = Path('/home/ayron/khs-ai-portfolio')
ASSET = '/assets/case-studies.css'
SITE = 'https://ayron.in'

ROUTES = [('/', 'Home'), ('/homelab/', 'Home Lab'), ('/networking/', 'Networking'), ('/ai/', 'AI & Development'), ('/projects/', 'Projects'), ('/tools/', 'Tools'), ('/about/', 'About')]

def header(current):
    links=''.join(f'<a href="{r}"'+(' aria-current="page"' if r==current else '')+f'>{escape(label)}</a>' for r,label in ROUTES)
    return f'''<a class="skip-link" href="#main-content">Skip to main content</a><header class="site-header"><div class="wrap nav"><a class="brand" href="/" aria-label="Ayron Jins home"><i class="brand-mark" aria-hidden="true"></i><span>AYRON JINS / LAB</span></a><nav class="nav-links" id="primary-nav" aria-label="Primary navigation">{links}</nav><div class="header-status"><i class="status-dot" aria-hidden="true"></i><span>SYSTEM: ONLINE</span></div><button class="menu" id="menu" type="button" aria-label="Open navigation" aria-controls="primary-nav" aria-expanded="false">☰</button></div></header>'''

def footer():
    links=''.join(f'<a href="{r}">{escape(label.upper())}</a>' for r,label in ROUTES)
    return f'<footer class="site-footer"><div class="wrap footer-row"><span><b>AYRON JINS / LAB</b> — Technology / Infrastructure / AI</span><span class="footer-nav">{links}<a href="mailto:Ayronjins4@gmail.com">EMAIL</a></span><span>SYSTEM: ONLINE · <span id="current-year">2026</span></span></div></footer>'

def meta(title, description, canonical, page_type='TechArticle'):
    return f'''<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(description, quote=True)}"><meta name="author" content="Ayron Jins"><meta name="creator" content="Ayron Jins"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="{canonical}"><link rel="alternate" hreflang="en" href="{canonical}"><link rel="alternate" hreflang="x-default" href="{canonical}"><link rel="alternate" type="text/plain" href="/llms.txt" title="AI-readable site summary"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fonts/dm-sans-latin.woff2" as="font" type="font/woff2" crossorigin><meta property="og:type" content="article"><meta property="og:site_name" content="Ayron Jins Engineering Portfolio"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description, quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{SITE}/assets/ayron-jins-portfolio-og.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title)}"><meta name="twitter:description" content="{escape(description, quote=True)}"><script type="application/ld+json">{{"@context":"https://schema.org","@type":"{page_type}","@id":"{canonical}#article","url":"{canonical}","headline":"{escape(title)}","description":"{escape(description)}","author":{{"@type":"Person","@id":"{SITE}/#ayron-jins","name":"Ayron Jins","url":"{SITE}/"}},"publisher":{{"@type":"Person","@id":"{SITE}/#ayron-jins","name":"Ayron Jins"}},"inLanguage":"en"}}</script><link rel="stylesheet" href="/assets/site.css?v=20260913"><link rel="stylesheet" href="{ASSET}"><script async src="/analytics/script.js" data-website-id="68eb35df-10a6-45d6-8f0f-3e3628b84cfc" data-host-url="{SITE}/analytics"></script><script src="/assets/site.js?v=20260913" defer></script>'''

def shell(route, title, description, page, body):
    return f'''<!DOCTYPE html><html lang="en"><head>{meta(title,description,SITE+route)}</head><body class="page page-case-study page-{page}">{header('/projects/')}<main id="main-content" tabindex="-1" class="page-main"><div class="page-routebar wrap"><a href="/projects/">← PROJECTS</a><span>FLAGSHIP / {page.upper()}</span></div>{body}</main>{footer()}</body></html>'''

def architecture(nodes, caption):
    cards=''.join(f'<div class="case-node"><small>{n[0]}</small><strong>{n[1]}</strong><span>{n[2]}</span></div>' for n in nodes)
    return f'<figure class="case-architecture"><div class="case-architecture-grid">{cards}</div><figcaption>{caption}</figcaption></figure>'

khs_body = f'''<section class="section case-hero" aria-labelledby="khs-title"><div class="wrap"><div class="section-head"><div><div class="section-kicker">KHS AI / FLAGSHIP CASE STUDY</div><h1 class="section-title" id="khs-title">From language model to controlled computer action.</h1><p class="section-intro">A current exhibition project by Ayron Jins exploring how an AI system can reason, use explicitly provided tools, observe results and remain inside visible permission boundaries.</p><div class="case-badges"><span>STATUS / <b>CURRENT PROJECT</b></span><span>SCOPE / <b>EXPERIMENTAL</b></span><span>EVIDENCE / <b>ARCHITECTURE + DESIGN</b></span></div></div><div class="section-index">CASE / 01</div></div></div></section>
<section class="section" aria-labelledby="khs-problem"><div class="wrap case-layout"><div><div class="section-kicker">01 / Problem</div><h2 class="section-title" id="khs-problem">Text can describe an action. A system must handle the consequences.</h2></div><div class="case-copy"><p>Most assistants stop at a generated response. KHS AI explores the engineering problem that appears when a language model participates in real digital work: the model needs tools, the tools need boundaries, and the resulting state needs to be inspected before the next decision.</p><p>The project is not presented as an unrestricted autonomous computer. Its central question is narrower and more useful: how can a model move through a controlled action loop while the user and the surrounding system retain visibility and control?</p></div></div></section>
<section class="section" aria-labelledby="khs-architecture"><div class="wrap"><div class="section-head"><div><div class="section-kicker">02 / Architecture</div><h2 class="section-title" id="khs-architecture">A loop with explicit capability boundaries.</h2><p class="section-intro">This is the architecture documented by the project. It describes the system relationship, not a claim that every path is deployed or autonomous.</p></div><div class="section-index">FLOW / 07</div></div>{architecture([('01 / INPUT','USER + CONTEXT','goal, constraints and current state'),('02 / REASONING','LLM / MODEL','interpret and propose the next action'),('03 / CONTROL','AGENT CONTROLLER','mediate policy, tools, state and verification'),('04 / CAPABILITY','TOOLS','explicit bridges to permitted systems'),('05 / EXECUTION','COMPUTER / APPS','perform the selected operation'),('06 / OBSERVATION','RESULT','return state, errors and evidence'),('07 / LOOP','VERIFY → DECIDE','continue, recover, stop or ask')],'Conceptual KHS AI flow: the controller is the boundary between model output and external effect.')}</div></section>
<section class="section" aria-labelledby="khs-boundaries"><div class="wrap"><div class="section-head"><div><div class="section-kicker">03 / Control model</div><h2 class="section-title" id="khs-boundaries">The controller is part of the product.</h2></div></div><div class="case-grid"><article class="case-panel"><h3>Capability is explicit</h3><p>Tools are controlled bridges, not an implied unrestricted shell. The available capability list should be visible, limited and updateable.</p></article><article class="case-panel"><h3>State is observed</h3><p>After an action, the system needs evidence about what changed. A successful command or click is not the same as a verified outcome.</p></article><article class="case-panel"><h3>Failure is a branch</h3><p>Errors, changed interfaces, missing dependencies and incomplete tasks are normal system states. The agent must be able to stop, recover or request input.</p></article><article class="case-panel"><h3>User control remains visible</h3><p>Permissions, action levels and verification state should be understandable to the person who owns the task.</p></article></div></div></section>
<section class="section" aria-labelledby="khs-implementation"><div class="wrap case-layout"><div><div class="section-kicker">04 / Implementation vocabulary</div><h2 class="section-title" id="khs-implementation">Build around the model, not only inside it.</h2></div><div class="case-copy"><p>The portfolio documents Python and automation, APIs/FastAPI where used, Docker/Linux, local model experimentation through Ollama, and Open WebUI as an interface. These are project vocabulary and areas of implementation or exploration, not a claim that every component is one deployed production path.</p><pre class="case-code"><code>agent:
  capabilities: explicit
  observe_after_action: true
  require_verification: true
  on_failure: recover_or_stop
  credentials: never_in_prompt</code></pre><p class="case-note">Representative policy sketch — no credentials, endpoints or live configuration are included.</p></div></div></section>
<section class="section" aria-labelledby="khs-testing"><div class="wrap"><div class="section-head"><div><div class="section-kicker">05 / Testing questions</div><h2 class="section-title" id="khs-testing">Evaluate the system, not just the answer.</h2></div></div><div class="case-grid case-grid-six">{''.join(f'<article class="case-panel"><span class="case-number">{i:02d}</span><h3>{title}</h3><p>{copy}</p></article>' for i,(title,copy) in enumerate([('Task completion','Did the intended goal finish?'),('Tool choice','Was an appropriate capability selected?'),('Recovery','Could the system continue after failure?'),('Safety','Did it stay within the declared boundaries?'),('Efficiency','Did it avoid unnecessary actions?'),('Consistency','Did it behave reasonably across repeated tasks?')],1))}</div></div></section>
<section class="section" aria-labelledby="khs-lessons"><div class="wrap case-layout"><div><div class="section-kicker">06 / Lessons and limits</div><h2 class="section-title" id="khs-lessons">Reliability is the surrounding system.</h2></div><div class="case-copy"><p>The project’s strongest lesson is architectural: model quality alone does not produce a reliable computer-operating system. Permissions, state, feedback, recovery and verification determine whether an action is useful.</p><p>This public case study intentionally does not claim users, adoption, benchmark scores, autonomous production deployment, institutional partnerships or completed device control. Real screenshots and configuration details should be added only after they are sanitized and verified.</p><p>Next directions are to test more bounded tasks, make action levels clearer, improve recovery paths and document failure cases without exposing private systems.</p></div></div></section>
<section class="page-next"><div class="wrap page-next-inner"><div><div class="section-kicker">Related infrastructure</div><h2>Where the agent runs.</h2><p>The homelab and network provide the boundaries that make the AI experiment concrete.</p></div><a class="btn btn-primary" href="/projects/homelab-networking/">Open homelab case study <span>→</span></a></div></section>'''

lab_body = f'''<section class="section case-hero" aria-labelledby="lab-title"><div class="wrap"><div class="section-head"><div><div class="section-kicker">HOME LAB + NETWORKING / FLAGSHIP CASE STUDY</div><h1 class="section-title" id="lab-title">Make the request path and the operating boundary visible.</h1><p class="section-intro">A factual operating note on Ayron Jins’s self-hosted environment: the services, request path, resource boundaries, monitoring and the storage-expansion incident that exposed an incomplete disk resize.</p><div class="case-badges"><span>STATUS / <b>OPERATED</b></span><span>HOST / <b>UBUNTU + KVM</b></span><span>EVIDENCE / <b>LIVE SERVICE CHECKS</b></span></div></div><div class="section-index">CASE / 02</div></div></div></section>
<section class="section" aria-labelledby="lab-problem"><div class="wrap case-layout"><div><div class="section-kicker">01 / Problem</div><h2 class="section-title" id="lab-problem">A service is only useful when its whole path can be explained.</h2></div><div class="case-copy"><p>A home lab turns infrastructure into a visible system: virtualization, Linux, containers, DNS, reverse proxies, storage, monitoring and backups meet at the same boundary. The challenge is not collecting software; it is knowing which layer failed when a request does not arrive, a service does not start, or an apparently expanded disk still has the old filesystem size.</p><p>The environment is intentionally described as a learning and operating system, not as enterprise infrastructure. Its value is the ability to build, break, trace and improve a real path.</p></div></div></section>
<section class="section" aria-labelledby="lab-flow"><div class="wrap"><div class="section-head"><div><div class="section-kicker">02 / Request flow</div><h2 class="section-title" id="lab-flow">From hostname to service, one boundary at a time.</h2><p class="section-intro">The edge path is conceptual; the host and service facts below are verified on the current server.</p></div><div class="section-index">PATH / 06</div></div>{architecture([('01 / NAME','DNS','resolve the requested hostname'),('02 / EDGE','ROUTER + NAT','reach the host boundary where applicable'),('03 / WEB','NGINX','select the hostname and route'),('04 / HOST','UBUNTU SERVER','processes, filesystems and services'),('05 / CONTAINERS','DOCKER','isolate application and database paths'),('06 / RESULT','HTTP RESPONSE','verify status, content and headers')],'Conceptual request path used for diagnosis; private addresses and router secrets are deliberately omitted.')}</div></section>
<section class="section" aria-labelledby="lab-verified"><div class="wrap"><div class="section-head"><div><div class="section-kicker">03 / Verified environment</div><h2 class="section-title" id="lab-verified">What is actually operating.</h2></div></div><div class="case-grid"><article class="case-panel"><span class="case-label">HOST</span><h3>Ubuntu on KVM</h3><p>Current host evidence reports Ubuntu 26.04.1 LTS, x86_64, 4 logical CPUs and 11 GiB RAM. The virtual disk is 260 GiB after expansion.</p></article><article class="case-panel"><span class="case-label">EDGE</span><h3>Nginx + HTTPS</h3><p>Nginx serves the ayron.in portfolio and preserves the independent pc.ayron.in dashboard and news.ayron.in service.</p></article><article class="case-panel"><span class="case-label">OBSERVABILITY</span><h3>Real checks</h3><p>Uptime checks verify the portfolio, robots, sitemap and preserved subdomains. Umami, Uptime Kuma and SEOnaut remain on loopback/private bindings.</p></article><article class="case-panel"><span class="case-label">CONTAINERS</span><h3>Bounded services</h3><p>Current SEO services use persistent databases, restart policies, resource controls, scheduled reports and local backups. Database ports are not public.</p></article></div></div></section>
<section class="section" aria-labelledby="lab-incident"><div class="wrap case-layout"><div><div class="section-kicker">04 / Incident report</div><h2 class="section-title" id="lab-incident">The virtual disk grew first. The filesystem did not.</h2></div><div class="case-copy"><p>The server reported a 260 GiB virtual disk, but inspection found a 62 GiB root partition, a 31 GiB root logical volume and an ext4 root filesystem with only about 4.2 GiB free.</p><p>The partition table was GPT. `/dev/sda3` was positively identified as the LVM physical volume, and the volume group showed approximately 31 GiB free before any resize. After backing up GPT and LVM metadata, only the identified path was expanded: partition 3, PV, root LV and ext4.</p><div class="case-metrics"><div><b>BEFORE</b><span>31G root LV · 4.2G free · 86% used</span></div><div><b>AFTER</b><span>258G root LV · 218G free · 11% used</span></div></div><p class="case-note">No partition was shrunk or deleted. The expansion was verified with `lsblk`, `findmnt`, LVM inspection and `df`.</p></div></div></section>
<section class="section" aria-labelledby="lab-operations"><div class="wrap"><div class="section-head"><div><div class="section-kicker">05 / Operating posture</div><h2 class="section-title" id="lab-operations">Observe → back up → change one boundary → verify.</h2></div></div><div class="case-grid case-grid-six">{''.join(f'<article class="case-panel"><span class="case-number">{i:02d}</span><h3>{title}</h3><p>{copy}</p></article>' for i,(title,copy) in enumerate([('Monitoring','Check availability and response paths at bounded intervals.'),('Crawling','Run SiteOne and SEOnaut as sensors, not as automatic change engines.'),('Performance','Use Lighthouse history to detect regressions, not to chase a perfect score.'),('Backups','Keep database dumps, configuration, reports and restoration metadata.'),('Security','Keep dashboards private, secrets local and capabilities narrow.'),('Diagnosis','Separate application, localhost, port, proxy, DNS and upstream failures.')],1))}</div></div></section>
<section class="section" aria-labelledby="lab-limits"><div class="wrap case-layout"><div><div class="section-kicker">06 / Lessons and next direction</div><h2 class="section-title" id="lab-limits">The useful architecture is the one that can be debugged.</h2></div><div class="case-copy"><p>The lab demonstrates how a request travels through boundaries, but it does not claim fixed enterprise topology, production-scale traffic, guaranteed uptime or public exposure for every documented service. Some portfolio diagrams remain conceptual and are labelled accordingly.</p><p>The next useful improvements are not more containers for their own sake: an external backup copy, private admin access through VPN/SSH, measured real-user data, and case studies tied to genuine project evidence.</p></div></div></section>
<section class="page-next"><div class="wrap page-next-inner"><div><div class="section-kicker">Related AI system</div><h2>Put intelligence inside the boundary.</h2><p>KHS AI explores controlled tools, observation and verification on top of this infrastructure vocabulary.</p></div><a class="btn btn-primary" href="/projects/khs-ai/">Open KHS AI case study <span>→</span></a></div></section>'''

(ROOT/'projects/khs-ai').mkdir(parents=True, exist_ok=True)
(ROOT/'projects/homelab-networking').mkdir(parents=True, exist_ok=True)
(ROOT/'projects/khs-ai/index.html').write_text(shell('/projects/khs-ai/','KHS AI Case Study | Ayron Jins','Evidence-based case study of KHS AI, an experimental controlled computer-operation AI project by Ayron Jins.', 'khs-ai', khs_body), encoding='utf-8')
(ROOT/'projects/homelab-networking/index.html').write_text(shell('/projects/homelab-networking/','Homelab and Networking Case Study | Ayron Jins','Evidence-based case study of Ayron Jins’s self-hosted homelab, network request path, operations and storage expansion.', 'homelab-networking', lab_body), encoding='utf-8')
print('built 2 flagship case studies')
